// ignore_for_file: unused_import

import 'package:flutter/material.dart';

List<String> indicatorone = [
  'I.R.A',
  'TUBERCULOSIS',
  'HIPERTENSIÓN ARTERIAL',
  'DIABETES MELLITUS',
  'EPOC',
  'CÁNCER',
  'VACUNACIÓN',
  'MUERTE PERINATAL',
  'VIVIENDA DIGNA',
  'AGUA POTABLE',
  'ALCANTARILLADO',
  'EDUCACIÓN',
  'REDES ELÉCTRICAS',
];

List<String> indicatortwo = [
  'MAPAS',
  'TALENTO HUMANO',
  'COMPUTADOR',
  'SOFTWARE',
  'INTERNET',
  'BASES DE DATOS',
];

List<String> indicatorthree = [
  'ALCOHOLISMO',
  'TALENTO HUMANO PARA INTERVENCIÓN',
  'CONSUMO SUSTANCIAS PSICOACTIVAS',
  'MAPA DE INDICADORES',
  'SUICIDIO',
];

List<String> indicatorfour = [
  'VOLANTES+WEB',
  'PERIFONEO/REDES',
  'CAMPAÑA DE AUTOCUIDADO',
  'EMISORA',
  'ART. SEC. EDUCACIÓN',
  'ART. SEC. CULTURA',
];

List<String> indicatorfive = [
  'CERCO EPIDEMIOLÓGICO',
  'IEC',
  'MAPA DE CASOS',
  'SEG. CLINICO-PACIENTES',
  'REPORTE CASOS A SECCIONAL',
  'BOLETÍN SEMANAL A COMUNIDAD',
];

List<String> indicatorsix = [
  'ATENCIÓN DE CONTROL PERINATAL',
  'MAPA',
  'SEGUIMIENTO ALTO RIESGO OBSTÉTRICO',
  'PARTO HUMANIZADO',
];

List<String> indicatorseven = [
  'SEGURIDAD ALIMENTARIA',
  'ADULTOS CON SUBSIDIO',
  'SALUD MENTAL DEL ADULTO MAYOR',
  'CENSO ADULTO MAYOR',
];

List<String> indicatoreight = [
  'INF. ARTICULACIÓN CON DLS',
  'DOTACIÓN DE E.P.P.',
  'PROTOCOLO ACTUALIZADO EN LA ESE',
  'SEGUIMIENTO A CASOS POSITIVOS',
  'FORTALECIMIENTO ATENCIÓN PRIMARIA',
];

List<String> indicatornine = [
  'B.D COMERCIANTES/TRANSPORTADORES',
  'REUNIÓN SEMANAL CON ALCALDE',
  'EQUIPO DE RESPUESTA COVID',
  'INFORME MENSUAL A LA DLS',
  'PROTOCOLOS DE BIOSEGURIDAD',
];

List<String> indicatorten = [
  'B.D COMERCIANTES/TRANSPORTADORES',
  'REUNIÓN SEMANAL CON ALCALDE',
  'EQUIPO DE RESPUESTA COVID',
  'INFORME MENSUAL A LA DLS',
  'PROTOCOLOS DE BIOSEGURIDAD',
];
